# Generated by Django 4.0.3 on 2022-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeboxapp', '0002_rename_article_recipe_alter_author_byline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='byline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
