# Generated by Django 4.0.3 on 2022-08-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeboxapp', '0003_rename_first_name_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='byline',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
