# Generated by Django 4.0.3 on 2022-08-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeboxapp', '0004_remove_author_byline_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
